### PR TITLE
static_parameter expr

### PR DESCRIPTION
**Pull request by KDr2**
Fix https://github.com/TuringLang/Libtask.jl/issues/174

### CODE REVIEW

**Review by willtebbutt — COMMENTED** [review]
This LGTM. You'll need to bump the version number before merging though so that we can tag a release.

**Comment by penelopeysm** [comment]
Yes, it does fix the examples in #174! To be precise, the first one still gives an error, but it now gives another error that isn't due to Libtape (it's a meaningless model after all).

**Comment by penelopeysm** [comment]
Haha, sorry, I just edited the comment (probably after you saw it) to say that I hadn't worked that one out yet. I'm looking at it now!

Thank you for looking into this so quickly!!

**Comment by penelopeysm** [comment]
@KDr2 I think it's the `::Type{T}` that makes this fail on master (but is fixed on this PR):

```julia
using Libtask
function g(::Type{T}) where {T}
    a = zeros(T, 10)
end
tf = Libtask.TapedFunction(g, Float64)
```

**Comment by penelopeysm** [comment]
```julia
using Libtask
function g(::Type{T}) where {T}
    a = zeros(T, 10)
end
tf = Libtask.TapedFunction(g, Float64)
```

The above seems fine, but then subsequently calling `r = tf(Float64)` fails, at least on <=1.10. This isn't a regression introduced by this PR, it's also on master.

**Comment by KDr2** [comment]
> This isn't a regression introduced by this PR, it's also on master.

Fixed, but what happened to the Integeration test? It passes now...

**Comment by penelopeysm** [comment]
It's probably because of Hong's commit which bumped the minor version, and Turing.jl's compat entry for Libtask doesn't allow it to be tested with this.

I'm curious as to whether we can keep 1.7 compat here, if you don't mind, I'll test it out :)

**Comment by KDr2** [comment]
> we can keep 1.7 compat

We can keep both 1.7 and 1.10 in the CI unit tests.

**Comment by penelopeysm** [comment]
Thank you again to all of you who contributed here ❤️

**Pull request merged**
